# Generated by Django 5.2.1 on 2025-05-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='history',
            field=models.JSONField(default=list),
        ),
    ]
