# Generated by Django 5.2.1 on 2025-05-20 08:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0002_chatsession_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
