# Generated by Django 5.2.1 on 2025-05-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0003_alter_chatsession_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='chunk_text',
            field=models.TextField(default=''),
        ),
    ]
