# Generated by Django 5.2.1 on 2025-05-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0005_chatsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
